# Generated by Django 4.2.16 on 2024-12-09 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
                ('duracao', models.DateField()),
                ('salario', models.PositiveIntegerField()),
                ('profissao', models.CharField(max_length=100)),
                ('documentos', models.ImageField(blank=True, null=True, upload_to='img')),
                ('tiposempr', models.CharField(blank=True, choices=[('CHAB', 'Crédito Habitacional'), ('CAUT', 'Crédito Automotivo'), ('CEST', 'Crédito Estudantil'), ('CPES', 'Crédito Pessoal')], max_length=100)),
                ('tempo', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
