# Generated by Django 4.2.11 on 2024-12-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="person",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
