# Generated by Django 4.2.11 on 2024-12-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_emprestimo_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="salario",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
