# Generated by Django 4.2.17 on 2024-12-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_emprestimo_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='creditscore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='decisao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
