# Generated by Django 5.1.3 on 2024-12-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emprestimo_creditscore_emprestimo_decisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=100)),
                ('id_emprestimo', models.PositiveIntegerField()),
            ],
        ),
    ]
