# Generated by Django 4.2.11 on 2024-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_emprestimo_salario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="id",
            field=models.CharField(
                default="default_id", max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
