# Generated by Django 4.2.11 on 2024-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_emprestimo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="id",
            field=models.UUIDField(
                default="default_id", primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
