# Generated by Django 5.1.3 on 2024-12-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_horarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='horarios',
            new_name='horario',
        ),
    ]
