# Generated by Django 5.1.3 on 2024-12-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_horarios_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='cliente_selecionou',
            field=models.BooleanField(default=False),
        ),
    ]
