# Generated by Django 4.2.11 on 2024-12-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_horario_cliente_selecionou"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="horario",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
